### ISSUE TITLE
Unnecessary SQLite Dependency

### ISSUE THREAD

**Issue by grbspltt** [maddy2get/express-brute-sequelize#8]
Unused SQLite dependency in source.  It is not listed as a dependency in package.json. However when using the module it will throw an error.

**Comment by minayousseif** [comment]
same here, I am having the same issue.

Error: Cannot find module 'sqlite3'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/api/node_modules/express-brute-sequelize/index.js:11:12)
    at Object.<anonymous> (/usr/src/api/node_modules/express-brute-sequelize/index.js:149:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/api/build/bundle.js:2:5719)
    at t (/usr/src/api/build/bundle.js:2:106)
    at Object.defineProperty.value (/usr/src/api/build/bundle.js:2:4637)
    at t (/usr/src/api/build/bundle.js:2:106)
    at Object.<anonymous> (/usr/src/api/build/bundle.js:2:1718)
    at t (/usr/src/api/build/bundle.js:2:106)
    at Object.defineProperty.value (/usr/src/api/build/bundle.js:2:3631)
    at t (/usr/src/api/build/bundle.js:2:106)
    at e.exports.development.app.port (/usr/src/api/build/bundle.js:2:506)
    at Object.<anonymous> (/usr/src/api/build/bundle.js:2:516)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by milesstanfield** [comment]
what a waste of time
